pull request check extended with description and comments check

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -1,34 +1,56 @@
 name: Pull request check
-
-on:
+on:   
   pull_request:
     types: [edited, synchronize, opened, reopened]
     branches: [ "main" ]
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  prcheck:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Check for description in PR
+        id: check-description
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-      - name: Fail
-        run: |
-          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
-          # exit 1
-          exit 0
-
+          # every pull request is an issue as well - we can address them through /issues/ endpoint
+          prbody=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}")
+          if [ $(echo "$prbody" | jq .body ) == "null" ]; then
+            echo "There is no description added to the PR."
+            echo "no_desc=true" >> $GITHUB_OUTPUT
+          else
+            echo "Comments are added to the PR."
+            echo "no_desc=false" >> $GITHUB_OUTPUT
+          fi
+        shell: bash
       
+      - name: Fail if no description
+        run: |
+          if [[ "${{ steps.check-description.outputs.no_desc }}" == "true" ]]; then
+           echo "No description added to the pull request. Failing the build."
+           exit 1
+          fi
+        shell: bash
+      
+      - name: Check for comments in PR
+        id: check-comments
+        run: |
+          # every pull request is an issue as well - we can address them through /issues/ endpoint
+          comments=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments")
+          if [ $(echo "$comments" | jq '. | length') -eq 0 ]; then
+            echo "There is no comment added to the PR."
+            echo "no_comments=true" >> $GITHUB_OUTPUT
+          else
+            echo "Comments are added to the PR."
+            echo "no_comments=false" >> $GITHUB_OUTPUT
+          fi
+        shell: bash
+        
+      - name: Fail if no comments
+        run: |
+          if [[ "${{ steps.check-comments.outputs.no_comments }}" == "true" ]]; then
+           echo "No comments added to the pull request. Failing the build."
+           exit 1
+          fi
+        shell: bash
+        
